"""
Property-based tests for StyleConstants.

These tests verify universal properties that should hold across all valid inputs
using the Hypothesis library for property-based testing.
"""

from hypothesis import given, strategies as st, settings
from design_system.style_constants import StyleConstants


# Feature: unified-design-system, Property 3: Opacity Clamping
@given(
    opacity=st.integers()
)
@settings(max_examples=100)
def test_opacity_clamping(opacity: int):
    """
    **Validates: Requirements 4.2**
    
    Property: For any integer opacity value (including values outside the valid range),
    when passed to clamp_opacity(), the result should be within the range [50, 255],
    with values below 50 clamped to 50 and values above 255 clamped to 255.
    """
    result = StyleConstants.clamp_opacity(opacity)
    
    # Result must always be in valid range [50, 255]
    assert 50 <= result <= 255, (
        f"Clamped opacity {result} is outside valid range [50, 255] for input {opacity}"
    )
    
    # Values below 50 should be clamped to 50
    if opacity < 50:
        assert result == 50, (
            f"Opacity {opacity} < 50 should be clamped to 50, got {result}"
        )
    
    # Values above 255 should be clamped to 255
    elif opacity > 255:
        assert result == 255, (
            f"Opacity {opacity} > 255 should be clamped to 255, got {result}"
        )
    
    # Values within range should remain unchanged
    else:
        assert result == opacity, (
            f"Opacity {opacity} within valid range should remain unchanged, got {result}"
        )


# Feature: unified-design-system, Property 3: Opacity Clamping - Boundary Conditions
@given(
    offset=st.integers(min_value=-10, max_value=10)
)
@settings(max_examples=100)
def test_opacity_clamping_boundaries(offset: int):
    """
    **Validates: Requirements 4.2**
    
    Property: Test boundary conditions around the min (50) and max (255) values.
    Values at 49 should clamp to 50, values at 256 should clamp to 255.
    """
    # Test lower boundary
    lower_test_value = 50 + offset
    lower_result = StyleConstants.clamp_opacity(lower_test_value)
    
    if lower_test_value < 50:
        assert lower_result == 50, (
            f"Value {lower_test_value} below 50 should clamp to 50, got {lower_result}"
        )
    elif lower_test_value <= 255:
        assert lower_result == lower_test_value, (
            f"Value {lower_test_value} in valid range should remain unchanged, got {lower_result}"
        )
    else:
        assert lower_result == 255, (
            f"Value {lower_test_value} above 255 should clamp to 255, got {lower_result}"
        )
    
    # Test upper boundary
    upper_test_value = 255 + offset
    upper_result = StyleConstants.clamp_opacity(upper_test_value)
    
    if upper_test_value < 50:
        assert upper_result == 50, (
            f"Value {upper_test_value} below 50 should clamp to 50, got {upper_result}"
        )
    elif upper_test_value <= 255:
        assert upper_result == upper_test_value, (
            f"Value {upper_test_value} in valid range should remain unchanged, got {upper_result}"
        )
    else:
        assert upper_result == 255, (
            f"Value {upper_test_value} above 255 should clamp to 255, got {upper_result}"
        )


# Feature: unified-design-system, Property 3: Opacity Clamping - Extreme Values
@given(
    opacity=st.one_of(
        st.integers(min_value=-1000000, max_value=-1),  # Large negative values
        st.integers(min_value=256, max_value=1000000),  # Large positive values
    )
)
@settings(max_examples=100)
def test_opacity_clamping_extreme_values(opacity: int):
    """
    **Validates: Requirements 4.2**
    
    Property: Test that very large negative and positive values are properly clamped.
    """
    result = StyleConstants.clamp_opacity(opacity)
    
    # Result must always be in valid range
    assert 50 <= result <= 255, (
        f"Clamped opacity {result} is outside valid range [50, 255] for extreme input {opacity}"
    )
    
    # Negative values should clamp to 50
    if opacity < 0:
        assert result == 50, (
            f"Negative opacity {opacity} should be clamped to 50, got {result}"
        )
    
    # Large positive values should clamp to 255
    else:
        assert result == 255, (
            f"Large opacity {opacity} should be clamped to 255, got {result}"
        )


# Feature: unified-design-system, Property 7: StyleConstants Color Consistency
@given(
    opacity=st.integers(min_value=50, max_value=255)
)
@settings(max_examples=100)
def test_color_consistency(opacity: int):
    """
    **Validates: Requirements 1.1, 3.3**
    
    Property: For any opacity value, the background color generated by
    StyleConstants.get_background_color(opacity) should use the RGB values
    (30, 30, 30) and format them as rgba(30, 30, 30, {opacity}).
    """
    result = StyleConstants.get_background_color(opacity)
    
    # Expected format with exact RGB values
    expected = f"rgba(30, 30, 30, {opacity})"
    
    # Verify the format is exactly as expected
    assert result == expected, (
        f"Background color format incorrect for opacity {opacity}. "
        f"Expected '{expected}', got '{result}'"
    )
    
    # Verify the result contains the correct RGB values
    assert "30, 30, 30" in result, (
        f"Background color should contain RGB values (30, 30, 30), got '{result}'"
    )
    
    # Verify the result is in rgba format
    assert result.startswith("rgba("), (
        f"Background color should start with 'rgba(', got '{result}'"
    )
    assert result.endswith(")"), (
        f"Background color should end with ')', got '{result}'"
    )
    
    # Verify the opacity value is present in the string
    assert str(opacity) in result, (
        f"Background color should contain opacity value {opacity}, got '{result}'"
    )
